# Default values for hound.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: etsy/hound
  tag: latest
  pullPolicy: IfNotPresent

service:
  # TODO: Ingress for external access
  # externalDns:
  # sslCertArn:

## Persist data to a persistent volume
persistence:
  enabled: true
  ## database data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "default"
  accessMode: ReadWriteOnce
  size: 500Gi
